### ISSUE TITLE
Bug/confusion of Etc/GMT timezones ?!

### ISSUE THREAD

**Issue by sefgit** [stub42/pytz#119]
How are timezones specified as `Etc/GMT#` to be used / understood ?

For example timezone 'Asia/Jakarta' is also known as GMT+7 timezone.
But following code shows that `Etc/GMT+7` and `Etc/GMT-7` seems to be **wrongly swapped**.

```
#!/usr/bin/env python3
import time
import pytz
from datetime import datetime

def main():
    #print('Timezones')
    #for timeZone in pytz.all_timezones:
    #    print(timeZone)
    # current Datetime
    _local = datetime.now()
    print('Timezone naive:\n', _local)
    _utc = datetime.now(pytz.utc)
    print('Timezone UTC:\n', _utc)
    _jakarta = datetime.now(pytz.timezone('Asia/Jakarta'))
    print('Timezone Asia/Jakarta:\n', _jakarta)
    _gmt_p7 = datetime.now(pytz.timezone('Etc/GMT+7'))
    print('Timezone Etc/GMT+7:\n', _gmt_p7)
    _gmt_p7_2 = _utc.astimezone(pytz.timezone('Etc/GMT+7'))
    print('Timezone Etc/GMT+7 ***:\n', _gmt_p7_2)
    _gmt_m7_2 = _utc.astimezone(pytz.timezone('Etc/GMT-7'))
    print('Timezone Etc/GMT-7 ***:\n', _gmt_m7_2)
    _gmt_m7 = datetime.now(pytz.timezone('Etc/GMT-7'))
    print('Timezone Etc/GMT-7:\n', _gmt_m7)

if __name__ == "__main__":
    main()
```

result:

```
Timezone naive:
 2024-02-13 16:21:51.508353
Timezone UTC:
 2024-02-13 09:21:51.510342+00:00
Timezone Asia/Jakarta:
 2024-02-13 16:21:51.629122+07:00
Timezone Etc/GMT+7:
 2024-02-13 02:21:51.631135-07:00
Timezone Etc/GMT+7 ***:
 2024-02-13 02:21:51.510342-07:00
Timezone Etc/GMT-7 ***:
 2024-02-13 16:21:51.510342+07:00
Timezone Etc/GMT-7:
 2024-02-13 16:21:51.635140+07:00
```

**Comment by bxparks** [comment]
They are intentionally swapped. See the following duplicate tickets:

- https://github.com/stub42/pytz/issues/64
- https://github.com/stub42/pytz/issues/60
- https://github.com/stub42/pytz/issues/41
- https://github.com/stub42/pytz/issues/37

All caused by this upstream decision:

- https://github.com/eggert/tz/blob/main/etcetera#L36

**Comment by sefgit** [comment]
Anyway ... it seems that it won't be fixed soon, so we got to live with it ;)

> It's not a BUG, it's by DESIGN ;)

[Time zone ETC/GMT sign value is inverted
](https://support.8x8.com/business-phone/analytics-for-work/Time_zone_ETC%2F%2FGMT_sign_value_is_inverted)

**Comment by bxparks** [comment]
> it seems that it won't be fixed soon, so we got to live with it ;)

It will likely never be "fixed" because doing so will break backwards compatibility.

The way I try to keep thing straight is that GMT+/-NN is the old POSIX with the sign reversal, and UTC+/-NN is the new hotness. But no, there is no `Etc/UTC+7` equivalent for `Etc/GMT-7`. As I recall, every time someone proposes to add those to TZDB, it gets shot down like a flaming Hindenburg.
