### ISSUE TITLE
2024.2: pytz.timezone() returns incorrect tzinfo data

### ISSUE THREAD

**Issue by andy-maier** [stub42/pytz#127]
Since pytz version 2024.2, `pytz.timezone()` returns incorrect data.

Example:
```
python
>>> import pytz
>>> from datetime import datetime
>>> dt = datetime(2017, 9, 5, 12, 13, 10, 0, pytz.timezone('CET'))
>>> dt.tzinfo
<DstTzInfo 'CET' LMT+0:18:00 STD>
>>> dt.isoformat()
'2017-09-05T12:13:10+00:18'
```

The CET timezone is UTC+1, so the `dt.tzinfo` value should have an offset of +01:00.

This was correct before version 2024.2.

We are circumventing this in our projects by excluding version 2024.2.

For a full test log that shows the failure due to the incorrect data, see https://github.com/zhmcclient/python-zhmcclient/actions/runs/10823820678/job/30029971748

**Comment by OguzUzman** [comment]
Yes, I can confirm as well that we're getting the same 18 minutes extra. Our solution was to exclude the version from pyproject.toml with:
```toml
pytz = "!=2024.2"
```

**Comment by ringsaturn** [comment]
From the [comparison] between 2024.1 and 2024.2](https://github.com/stub42/pytz/compare/release_2024.1...release_2024.2), I found nothing change in pytz it self.

Seems a change from upstream tzdb?

**Comment by stub42** [comment]
There are two issues here.

Firstly, per [pytz documentation](https://github.com/stub42/pytz/tree/master/src), the localized timestamp is being created incorrectly. _"This library differs from the documented Python API for tzinfo implementations; if you want to create local wallclock times you need to use the localize() method documented in this document."_ The awful API was necessary when pytz was first implemented, over 20 years ago.  This is the correct way of creating localized or wallclock timestamps with pytz.

```python
Python 3.8.10 (default, Jul 29 2024, 17:02:10)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytz
>>> pytz.__version__
'2024.2'
>>> from datetime import datetime
>>> cet = pytz.timezone('CET')
>>> dt = cet.localize(datetime(2017, 9, 5, 12, 13, 10, 0))
>>> dt.isoformat()
'2017-09-05T12:13:10+02:00'
>>> dt.tzinfo
<DstTzInfo 'CET' CEST+2:00:00 DST>
```

The second issue is that CET is a long deprecated timezone identifier per the IANA timezone database, and only works because of backwards compatibility. CET is the sort of identifier used on System V systems back in the 90s. Supported IANA identifiers are all in the format of Continent/City, such as Europe/Berlin.

```python
>>> cet = pytz.timezone('Europe/Berlin')
>>> dt = cet.localize(datetime(2017, 9, 5, 12, 13, 10, 0))
>>> dt.isoformat()
'2017-09-05T12:13:10+02:00'
```

**Comment by OguzUzman** [comment]
@stub42 correct me if I'm wrong. `localize` method returns the correct value as you specified but the `repr` returned by the timezone object is still wrong:
```python
>>> # This is wrong
>>> print(repr(pytz.timezone('Europe/Berlin')))
<DstTzInfo 'Europe/Berlin' LMT+0:53:00 STD>
>>> # This is correct
>>> pytz.timezone('Europe/Berlin').localize(datetime(2020, 1, 5, 8, 0))
datetime.datetime(2020, 1, 5, 8, 0, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>)
```

**Comment by stub42** [comment]
`pytz.timezone('Europe/Berlin')` has no date for context, and `repr` shows what the database records as the earliest timezone definition (Local Mean Time in 1893). The localize method is there to adjust the `tzinfo` to the correct one for a particular `datetime`.

```python
>>> from datetime import datetime
>>> cet = pytz.timezone('Europe/Berlin')
>>> print(cet)
Europe/Berlin
>>> print(repr(cet))
<DstTzInfo 'Europe/Berlin' LMT+0:53:00 STD>
>>> dt = cet.localize(datetime(2020,1,5,8,0))
>>> print(dt.tzinfo)
Europe/Berlin
>>> print(repr(dt.tzinfo))
<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>
```
